//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aesJuniorProjectT.Entities.Shared.Net45.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int application_id { get; set; }
        public string name { get; set; }
        public Nullable<int> ssn { get; set; }
        public string address { get; set; }
        public Nullable<int> phoneNumber { get; set; }
        public string positions_applied { get; set; }
        public Nullable<decimal> salaryExpectation { get; set; }
        public Nullable<bool> fullTime { get; set; }
        public Nullable<int> mondayAvailable { get; set; }
        public Nullable<int> tuesdayAvailable { get; set; }
        public Nullable<int> wednesdayAvailable { get; set; }
        public Nullable<int> thursdayAvailable { get; set; }
        public Nullable<int> fridayAvailable { get; set; }
        public Nullable<int> saturdayAvailable { get; set; }
        public Nullable<int> sundayAvailable { get; set; }
        public Nullable<int> mostRecent_id { get; set; }
        public Nullable<int> middleRecent_id { get; set; }
        public Nullable<int> leastRecent_id { get; set; }
        public Nullable<int> recentEducation_id { get; set; }
        public Nullable<int> middleEducation_id { get; set; }
        public Nullable<int> leastEducation_id { get; set; }
        public Nullable<int> reference_id { get; set; }
        public Nullable<System.DateTime> application_date { get; set; }
    }
}
