//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aesJuniorProjectT.Entities.Shared.Net45.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int education_id { get; set; }
        public string schoolName { get; set; }
        public string schoolAddress { get; set; }
        public Nullable<System.DateTime> timeAttended { get; set; }
        public Nullable<System.DateTime> timeLeft { get; set; }
        public Nullable<bool> graduated { get; set; }
        public string degreeMajor { get; set; }
    }
}
