//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aesJuniorProjectT.Entities.Shared.Net45.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public int reference_id { get; set; }
        public string reference_name { get; set; }
        public Nullable<int> reference_phone { get; set; }
        public string reference_company { get; set; }
        public string reference_title { get; set; }
    }
}
