//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aesJuniorProjectT.Entities.Shared.Net45.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int test_id { get; set; }
        public string question_list { get; set; }
        public Nullable<int> passingScore { get; set; }
    }
}
